# Generated by Django 5.0.3 on 2026-03-22 22:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=220, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_virtual", models.BooleanField(default=False)),
                ("location", models.CharField(blank=True, max_length=300)),
                ("location_url", models.URLField(blank=True)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                (
                    "max_capacity",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Número máximo de asistentes. Vacío = sin límite.",
                        null=True,
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="events/covers/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("published", "Publicado"),
                            ("closed", "Cerrado"),
                            ("cancelled", "Cancelado"),
                            ("finalized", "Finalizado"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organizer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="organized_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
                "db_table": "events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status"], name="events_status_8890b6_idx"),
                    models.Index(
                        fields=["start_date"], name="events_start_d_6c01fc_idx"
                    ),
                    models.Index(
                        fields=["organizer"], name="events_organiz_1c7a2e_idx"
                    ),
                ],
            },
        ),
    ]
