# Generated by Django 5.0.3 on 2026-04-06 21:22

from django.db import migrations, models


def populate_modality_from_is_virtual(apps, schema_editor):
    """Copy is_virtual → modality before removing the old field."""
    Event = apps.get_model('events', 'Event')
    Event.objects.filter(is_virtual=True).update(modality='virtual')
    Event.objects.filter(is_virtual=False).update(modality='in_person')


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        # 1. Add modality with a safe default first (before removing is_virtual)
        migrations.AddField(
            model_name="event",
            name="modality",
            field=models.CharField(
                choices=[
                    ("in_person", "Presencial"),
                    ("virtual", "Virtual"),
                    ("hybrid", "Híbrido"),
                ],
                default="in_person",
                max_length=20,
            ),
        ),
        # 2. Populate modality from the existing is_virtual flag
        migrations.RunPython(
            populate_modality_from_is_virtual,
            reverse_code=migrations.RunPython.noop,
        ),
        # 3. Now safe to remove the old field
        migrations.RemoveField(
            model_name="event",
            name="is_virtual",
        ),
        migrations.AddField(
            model_name="event",
            name="virtual_access_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
