# Generated by Django 5.0.3 on 2026-04-06 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_add_modality_and_virtual_access_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="hero_image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
