# Generated by Django 5.0.3 on 2026-04-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_add_hero_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="audience_type",
            field=models.CharField(
                blank=True,
                choices=[("internal", "Interno"), ("external", "Externo")],
                help_text="Interno: empleados. Externo: clientes/prospectos.",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="target_company",
            field=models.CharField(
                blank=True,
                help_text="Empresa destinataria del evento privado externo.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="visibility",
            field=models.CharField(
                choices=[("public", "Público"), ("private", "Privado")],
                db_index=True,
                default="public",
                help_text="Público: visible para todos. Privado: solo por invitación.",
                max_length=10,
            ),
        ),
    ]
