# Generated by Django 5.0.3 on 2026-04-07 19:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0004_add_visibility_audience_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationFormField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=200)),
                ('field_type', models.CharField(choices=[('text', 'Texto corto'), ('textarea', 'Texto largo'), ('email', 'Email'), ('phone', 'Teléfono'), ('select', 'Lista de opciones'), ('checkbox', 'Casilla de verificación'), ('number', 'Número')], default='text', max_length=20)),
                ('placeholder', models.CharField(blank=True, max_length=200)),
                ('is_required', models.BooleanField(default=False)),
                ('is_enabled', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('options', models.JSONField(blank=True, default=list, help_text="Lista de opciones para tipo select: ['Opción A', 'Opción B']")),
                ('field_key', models.SlugField(help_text="Identificador interno del campo. Ej: 'cargo', 'empresa'", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='events.event')),
            ],
            options={
                'db_table': 'registration_form_fields',
                'ordering': ['order', 'created_at'],
                'unique_together': {('event', 'field_key')},
            },
        ),
    ]
