# Generated by Django 5.0.3 on 2026-04-01 02:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
        ("registrations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email_type",
                    models.CharField(
                        choices=[
                            ("confirmation", "Confirmación de Registro"),
                            ("reminder_24h", "Recordatorio 24h"),
                            ("reminder_1h", "Recordatorio 1h"),
                            ("post_event", "Post-evento"),
                            ("manual", "Envío Manual"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("recipient_email", models.EmailField(max_length=254)),
                ("recipient_name", models.CharField(max_length=200)),
                ("subject", models.CharField(max_length=300)),
                (
                    "status",
                    models.CharField(
                        choices=[("sent", "Enviado"), ("failed", "Fallido")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_logs",
                        to="events.event",
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_logs",
                        to="registrations.registration",
                    ),
                ),
            ],
            options={
                "db_table": "email_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event", "email_type"],
                        name="email_logs_event_i_699dac_idx",
                    ),
                    models.Index(
                        fields=["registration", "email_type"],
                        name="email_logs_registr_63c769_idx",
                    ),
                ],
            },
        ),
    ]
