# Generated by Django 5.0.3 on 2026-04-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emaillog",
            name="email_type",
            field=models.CharField(
                choices=[
                    ("confirmation", "Confirmación de Registro"),
                    ("reminder_24h", "Recordatorio 24h"),
                    ("reminder_1h", "Recordatorio 1h"),
                    ("post_event", "Post-evento"),
                    ("manual", "Envío Manual"),
                    ("cancellation", "Cancelación"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
