# Generated by Django 5.0.3 on 2026-04-06 21:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="cancellation_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
