# Generated by Django 5.0.3 on 2026-04-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_registration_cancellation_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='form_responses',
            field=models.JSONField(blank=True, default=dict, help_text='Respuestas a campos dinámicos. {field_key: valor}'),
        ),
    ]
